name: Java Build Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  # =========================
  # 1. BUILD
  # =========================
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Java project
        run: mvn clean package -DskipTests


  # =========================
  # 2. TEST
  # =========================
  test:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run JUnit 5 tests
        run: mvn test